version: '3'

volumes:
  ecosystem-data:
  rabbitmq-data:

services:
  core:
    build: ./core/
    volumes:
      ecosystem-data: /data
    environment:
      SQLITE_DATABASE: '/data/database.sqlite'

  sqlite:
    image: coleifer/sqlite-web:latest
    volumes:
      ecosystem-data: /data    
    ports:
      - 8080:8080
    environment:
      SQLITE_DATABASE: "/data/database.sqlite"

  minio:
    image: quay.io/minio/minio server
    ports:
      - 10000:9000 
      - 10001:9001 
    volumes:
      ecosystem-data: /data
      MINIO_ROOT_USER: roottoor
      MINIO_ROOT_PASSWORD: toorroot

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        rabbitmq-data: /var/lib/rabbitmq/
    networks:
      - default

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      TZ: Europe/Lisbon
      MAILDEV_WEB_PORT: 1080
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_OUTGOING_USER: your_username
      MAILDEV_OUTGOING_PASS: your_password
    ports:
      - "8080:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"    
    networks:
      - default

  broker-emiter:
    build: ./mail-broker/broker-emiter
    restart: always
    environment:
      RABBIT_SERVER: rabbitmq      
    ports:
      - 5000:5000
    networks:
      - default

  broker-consumer:
    restart: always
    build: ./mail-broker/broker-consumer
    environment:
      RABBIT_SERVER: rabbitmq
      MAIL_SERVER: maildev
    networks:
      - default

  frontend:
    restart: always
    build: ./frontend/
    environment:
      core-api: 'http://localhost:3000'
      mail-api: 'http://localhost:5000'
